# Configuration Codemagic pour Medica Sign (Placé à la racine du dépôt)
# Ce fichier automatise les builds Android et iOS

workflows:
  ios-android-build:
    name: Build Medica Sign (Android & iOS)
    max_build_duration: 60
    instance_type: mac_mini_m2
    working_directory: mobile # Indique à Codemagic d'entrer dans le dossier mobile
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Configuration de l'environnement
        script: | 
          flutter pub get
      
      - name: Build Android (APK Release)
        script: | 
          flutter build apk --release
      
      - name: Build iOS Simulator (pour Appetize)
        script: | 
          flutter build ios --simulator --debug --no-codesign
      
      - name: Build iOS IPA (pour iPhone)
        script: | 
          flutter build ipa --debug --no-codesign

    artifacts:
      - mobile/build/app/outputs/flutter-apk/*.apk
      - mobile/build/ios/iphonesimulator/*.app
      - mobile/build/ios/ipa/*.ipa
    
    publishing:
      email:
        recipients:
          - moeztazkobbi@gmail.com
          - moetazkobbi@gmail.com
