server {
    listen 80;
    server_name medicasign.medicacom.tn;

    # Point vers le build React
    root /var/www/medica_sign/clientweb/build;
    index index.html;

    # Gère le routage React
    location / {
        try_files $uri /index.html;
        
        # Headers pour tenter de lever les blocages réseaux privés (CORS)
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Private-Network' 'true' always;
    }

    # Proxy API
    location /api {
        proxy_pass http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;
    }

    # Logs pour le debug
    access_log /var/log/nginx/medica_sign_access.log;
    error_log /var/log/nginx/medica_sign_error.log;
}
