server {
    listen 80;
    server_name medicasign.work.gd 51.178.39.67;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name medicasign.work.gd;

    ssl_certificate /etc/letsencrypt/live/medicasign.work.gd/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/medicasign.work.gd/privkey.pem;

    root /var/www/medica_sign/clientweb/build;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /api {
        proxy_pass http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
