server {
    listen 80;
    server_name medicasign.medicacom.tn 51.178.39.67;

    # Redirect HTTP to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name medicasign.medicacom.tn;

    ssl_certificate /etc/letsencrypt/live/medicasign.medicacom.tn/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/medicasign.medicacom.tn/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    root /var/www/medica_sign/clientweb/build;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Explicit fix for static files in React build
    location /static/ {
        root /var/www/medica_sign/clientweb/build;
        expires 1y;
        add_header Cache-Control "public";
    }

    location /api/ {
        proxy_pass http://localhost:5000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    charset utf-8;
    access_log /var/log/nginx/medica_sign.access.log;
    error_log /var/log/nginx/medica_sign.error.log;
}
